### PR TITLE
Migrate to slash commands

### LINKED ISSUE #21: Standardize Error Handling
Right now both the `!docs` and `!wiki` commands may encounter errors during their execution. Since that may happen as well with future additions, we should find a standardized way of dealing with exceptions during program executions in order to stay consistent.

### LINKED ISSUE #50: Use slash commands

### PR DESCRIPTION
**Pull request by Vampire**
Fixes #50
Fixes #21

This also allows to archive the #talk-to-james channel,
as I made all commands by default ephemeral with the option to answer to everyone.

### CODE REVIEW

**Review by Saladoc — COMMENTED** [review]
Do you think we should have a "listener" for the old !commands displaying an info message redirecting users to /commands? At least for some time. It might prevent some confusion.

**Comment by KILLEliteMaste** [comment]
> Do you think we should have a "listener" for the old !commands displaying an info message redirecting users to /commands? At least for some time. It might prevent some confusion.

I don't think we need to do this. Most users use James in his channels and once you see 2 or 3 commands using slash commands, it is quiet obvious for other too

**Review by KILLEliteMaste — COMMENTED** [review]
I think it would be nice for the `wiki` and `docs` command to have auto completion for the search term. With this you would get much faster accurate results

**Comment by Vampire** [comment]
> Do you think we should have a "listener" for the old !commands displaying an info message redirecting users to /commands? At least for some time. It might prevent some confusion.

I think it is a good idea, I added a migrated notification that reacts to all old commands the rest of the year.

> I don't think we need to do this. Most users use James in his channels and once you see 2 or 3 commands using slash commands, it is quiet obvious for other too

I don't think that is the case, as my intention is to get rid of #talk-to-james as I made all commands ephemeral by default with the option to show to everyone like described above.

> I think it would be nice for the wiki and docs command to have auto completion for the search term. With this you would get much faster accurate results

I'm not sure whether that will work out properly.
Both searches involve remote calls, so it might be too slow for good auto-completion.
Also the search-term is not really the result.
I think we can probably start out without it and you are welcome to contribute it, or maybe I'll have a look at some time.

**Review by Saladoc — APPROVED** [review]
LGTM

**Comment by Vampire** [comment]
@KILLEliteMaste do you want to also have another look?

**Review by KILLEliteMaste — APPROVED** [review]
Can't really say anything about your command framework specific things because I never used it, bedsides that this LGTM!

**Pull request merged**
